crearchitex_homepage:
    path:     /
    defaults: { _controller: ISLCrearchitexBundle:Default:index }

crearchitex_equipe:
    path:     /equipe
    defaults: { _controller: ISLCrearchitexBundle:Default:equipe }

crearchitex_projet:
    path:     /projet
    defaults: { _controller: ISLCrearchitexBundle:Default:projet }

crearchitex_news:
    path:     /news
    defaults: { _controller: ISLCrearchitexBundle:Default:news }

crearchitex_contact:
    path:     /contact
    defaults: { _controller: ISLCrearchitexBundle:Default:contact }

crearchitex_admin:
    path:     /admin
    defaults: { _controller: ISLCrearchitexBundle:Admin:admin }

crearchitex_admin_equipe_liste:
    path:     /admin/equipe
    defaults: { _controller: ISLCrearchitexBundle:Admin:equipeListe }
    
crearchitex_equipe_ajouter:
    path:     /admin/equipe-ajouter
    defaults: { _controller: ISLCrearchitexBundle:Admin:equipeAjouter }

crearchitex_equipe_modifier:
    path:     /admin/equipe-modifier/{id}
    defaults: { _controller: ISLCrearchitexBundle:Admin:equipeModifier, id:null }

crearchitex_equipe_supprimer:
    path:     /admin/equipe-supprimer/{id}
    defaults: { _controller: ISLCrearchitexBundle:Admin:equipeSupprimer, id:null }