services:
    isl_crearchitex.provider.test:
        class: ISL\CrearchitexBundle\Faker\Provider\Creafaker
        arguments: ["@davidbadura_faker.faker"]
      #  tags:
      #      -  { name: davidbadura_faker.provider }

#    isl_crearchitex.example:
#        class: ISL\CrearchitexBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
